# ExpTimer v2.0.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

default:
  seconds: 600
  readySeconds: 10
  commandsOnStart: []
  commandsOnEnd: []
  countdownOnStart: 3
  countdownOnEnd: 5
  useExpBar: true
  repeat: false
  endWithCTTeamDefeat: false
  endWithCTLeaderDefeat: false
  endWithCTKillTrophy: false

Timer1:
  seconds: 100
  readySeconds: 10
  commandsOnStart: ['say hardmode start!!', 'difficulty 4']
  commandsOnEnd: ['say hardmode timer1 end!!', 'difficulty 0']

Timer2:
  seconds: 1200
  readySeconds: 10
  commandsOnStart: ['say server open!', 'whitelist off']
  commandsOnEnd: ['say game over!', 'whitelist on']
  countdownOnStart: 5
  countdownOnEnd: 10
  useExpBar: false

Timer3:
  seconds: 10
  readySeconds: 10
  countdownOnStart: 1
  countdownOnEnd: 1

