# ExpTimer v2.2.0
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

default:
  seconds: 600
  readySeconds: 10
  commandsOnStart: []
  commandsOnEnd: []
  countdownOnStart: 3
  countdownOnEnd: 5
  playSound: true
  useExpBar: true
  endWithCTTeamDefeat: false
  endWithCTLeaderDefeat: false
  endWithCTKillTrophy: false

Timer1:
  seconds: 100
  readySeconds: 10
  commandsOnStart: ['say hardmode start!!', 'difficulty 4']
  commandsOnEnd: ['say hardmode timer1 end!!', 'difficulty 0']

Timer2:
  seconds: 1200
  readySeconds: 10
  commandsOnStart: ['say server open!', 'whitelist off']
  commandsOnEnd: ['say game over!', 'whitelist on']
  countdownOnStart: 5
  countdownOnEnd: 10
  playSound: false
  useExpBar: false

Timer3:
  seconds: 10
  readySeconds: 10
  countdownOnStart: 1
  countdownOnEnd: 1

infiniteTimer:
  seconds: 20
  readySeconds: 0
  commandsOnStart: ['say start!']
  commandsOnEnd: []
  countdownOnStart: 0
  countdownOnEnd: 0
  playSound: true
  nextConfig: 'infiniteTimer'

