# ExpTimer v2.2.3
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

default:
  seconds: 600
  readySeconds: 10
  commandsOnStart: []
  commandsOnEnd: []
  consoleCommandsOnStart: []
  consoleCommandsOnEnd: []
  countdownOnStart: 3
  countdownOnEnd: 5
  playSound: true
  useExpBar: true
  endWithCTTeamDefeat: false
  endWithCTLeaderDefeat: false
  endWithCTKillTrophy: false

ColorTeaming:
  seconds: 150
  readySeconds: 10
  commandsOnEnd: ['say Battle Start!!']
  consoleCommandsOnStart: ['rc', 'cclass all Knight', 'ctp all spawn']
  commandsOnEnd: ['say Battle End!!']
  consoleCommandsOnEnd: ['tp @a 0 65 0', 'clear @a', 'ct removeall']
  countdownOnStart: 3
  countdownOnEnd: 5
  playSound: true
  useExpBar: true
  endWithCTTeamDefeat: true
  endWithCTLeaderDefeat: true
  endWithCTKillTrophy: true

Timer1:
  seconds: 100
  readySeconds: 10
  commandsOnStart: ['say hardmode start!!', 'difficulty 4']
  commandsOnEnd: ['say hardmode timer1 end!!', 'difficulty 0']

Timer2:
  seconds: 1200
  readySeconds: 10
  commandsOnStart: ['say server open!']
  consoleCommandsOnStart: ['whitelist off']
  commandsOnEnd: ['say game over!']
  consoleCommandsOnEnd: ['kick @a', 'whitelist on']
  countdownOnStart: 5
  countdownOnEnd: 10
  playSound: false
  useExpBar: false

Timer3:
  seconds: 10
  readySeconds: 10
  countdownOnStart: 1
  countdownOnEnd: 1

infiniteTimer:
  seconds: 20
  readySeconds: 0
  commandsOnStart: ['say start!']
  commandsOnEnd: []
  countdownOnStart: 0
  countdownOnEnd: 0
  playSound: true
  nextConfig: 'infiniteTimer'

