# ExpTimer v1.1.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

defaultSeconds: 600
defaultReadySeconds: 10
commandsOnStart: ['say start!!']
commandsOnEnd: ['say end!!']
countdownOnStart: 3
countdownOnEnd: 5
useExpBar: true
