name: ExpTimer
main: com.github.ucchyocean.et.ExpTimer
version: 2.2.6
author: ucchy
description: 経験値バータイマー
softdepend: [ColorTeaming]
commands:
  exptimer:
    description: 経験値バータイマーコマンド
    aliases: [et,timer]
    usage: |
           /<command> start (seconds) [readySeconds] - 経験値バータイマーを開始する
           /<command> start (TimerName) - 指定したタイマーを開始する
           /<command> pause - 経験値バータイマーを一旦停止する
           /<command> cancel - 経験値バータイマーを終了する(終了時コマンドを実行しない)
           /<command> end - 経験値バータイマーを終了する(終了時コマンドを実行する)
           /<command> status - 現在の設定を表示する
           /<command> list - 実行可能なコンフィグのリストを表示する
           /<command> reload - config.yml をリロードする
    permission: exptimer
    permission-message: パーミッション "<permission>" がないため、コマンドを実行できません。
permissions:
  exptimer:
    description: 経験値バータイマーコマンドパーミッション
    default: true
  exptimer.start:
    description: startコマンドパーミッション
    default: op
  exptimer.pause:
    description: pauseコマンドパーミッション
    default: op
  exptimer.cancel:
    description: cancelコマンドパーミッション
    default: op
  exptimer.end:
    description: endコマンドパーミッション
    default: op
  exptimer.status:
    description: statusコマンドパーミッション
    default: op
  exptimer.list:
    description: listコマンドパーミッション
    default: op
  exptimer.reload:
    description: reloadコマンドパーミッション
    default: op
  exptimer.*:
    children:
      exptimer: true
      exptimer.start: true
      exptimer.pause: true
      exptimer.cancel: true
      exptimer.end: true
      exptimer.status: true
      exptimer.list: true
      exptimer.reload: true
    description: exptimerのサブノードの全パーミッション
